Logic wizard app
Momir-Radovanovic-EY/ey-mission-to-mars pull request #4
Opened 2021-07-16 16:17 UTC by Momir-Radovanovic-EY

Hi all,
I tried to implement all wizard Logic from documentation to this PR.
Added some new stuff like useMemo() hook, propTypes, hope in a right way.
Happy Friday everyone.

2021-07-16 19:06 UTC, mitrovic-jovana commented on src/components/WizardLayout/WizardLayout.js
>  const WizardLayout = ({
Great job on adding form wrapper!

2021-07-16 19:06 UTC, mitrovic-jovana commented on src/containers/AppWizzardForm/FirstWizardStep/FirstWizardStep.js
> +          <option value="Mr">Mr</option>
Maybe you can store all titles as array in some constant

2021-07-16 19:07 UTC, mitrovic-jovana commented on src/containers/AppWizzardForm/SecondWizardStep/SecondWizardStep.js
> +  }, [userData, fetchedStates, loadingStates]);
If logic inside useEffect does not depend an all properties in userData object, maybe it would be good to add in dependency array just properties on which it depends. In this case, useEffect is fired every time userData object changes, for example, it will fire when you are changing email even though you are just setting states here

2021-07-16 19:07 UTC, mitrovic-jovana commented on src/containers/AppWizzardForm/SecondWizardStep/SecondWizardStep.js
> +  }, [userData, loadingPostalcodes]);
The same thing as in the comment above. Read this [article ](https://www.benmvp.com/blog/object-array-dependencies-react-useEffect-hook/), maybe useMemo would be good option here too.

2021-07-16 19:07 UTC, mitrovic-jovana commented on src/containers/AppWizzardForm/SecondWizardStep/SecondWizardStep.js
> +            postalcodes.map((zipCode, index) => {
You can reduce your code here by destructuring zipCode here directly and using implicit return

2021-07-16 19:08 UTC, mitrovic-jovana commented on src/containers/AppWizzardForm/ThirdWizardStep/ThirdWizardStep.js
> +    if (userData.doesHaveAgricultureSkills) {
You can reduce your code here by removing if else statement and just setting textarea to userData.doesHaveAgricultureSkills

2021-07-16 19:08 UTC, mitrovic-jovana commented on src/containers/AppWizzardForm/ThirdWizardStep/ThirdWizardStep.js
> +    if (userData.doesHaveMetalworkSkills) {
The same thing as in the comment above

2021-07-16 19:10 UTC, mitrovic-jovana commented on src/containers/AppWizzardForm/ThirdWizardStep/ThirdWizardStep.js
> +              disabled={userData.isConvicted ? false : true}
No need for ternary operator here, just set disabled to !userData.isConvicted

2021-07-16 19:11 UTC, mitrovic-jovana commented on src/containers/AppWizzardForm/ThirdWizardStep/ThirdWizardStep.js
> +              id={index}
It's a anti pattern to use array index as id, since this is not a static list. Read this [article](https://medium.com/wesionary-team/using-index-as-a-key-is-an-anti-pattern-in-react-8e5db3aea3a9)

2021-07-16 19:12 UTC, mitrovic-jovana commented on src/containers/AppWizzardForm/ThirdWizardStep/ThirdWizardStep.js
> +              disabled={userData.isConvicted ? false : true}
The same thing for !userData.isConvicted

2021-07-16 19:16 UTC, mitrovic-jovana commented on src/shared/constants/actionTypes.js
> +export const NASA_DATA_REQUEST = "NASA_DATA_REQUEST";
It's a good practice to store all redux related files in one folder, so I would move this to redux folder.

2021-07-16 19:25 UTC, mitrovic-jovana requested changes
Really good job Momir! UI looks great and code structure is really neat, you really did a great work on making small reusable components. Also, kudos for using some more advanced concepts like useMemo.

Some things could be improved, here's what I noticed:
-	Show error message in red color and below input field. Some of the fields already have text above it, so it’s a little bit hard to spot the error message. Just a suggestion for better UX
-	Trim strings – I was able to populate input fields with spaces and I passed the frontend validation. 
-	Address 2 is not supposed to be mandatory field, check wireframes
-	Maybe it would be better to have the same logic for city input as for states and postal codes – input field that shows suggestions when you are typing. Since list of cities is very long for almost every state, I think it would look nicer without the dropdown, just a suggestion
-	Scenario on form 2: Select state, select city, change state -> zip code field gets enabled when I selected city, but even though I changed state I can still choose zip codes for the previous one
-	Input fields for state and zip codes need more validation. Even though I am getting suggestions for them, nothing is stopping me to type whatever I want and to pass validation. I see backend is not complaining when I do that, but it would be good to forbit that behavior on frontend 
-	Form 3: When you check yes for agriculture skills next question is mandatory and you are not validating that. The same thing goes for metalwork skills
-	I am getting an error when I pass false for isConvicted property. I think it’s because you are passing array with one object, even though in that object forWhat and convictionDate fields are empty strings. I tried in postman to send just empty array or not to send “convictions” property and it’s ok. Do some investigation on that
-	When I navigate back from form 3 and come back again properties are empty. Back functionality works as expected on other form, so take a look for the form 3 if you are missing something

Overall really good job, just spend some tome on testing scenarios I mentioned above. That can be upgraded

2021-07-16 19:29 UTC, mitrovic-jovana commented on src/components/WizardLayout/WizardLayout.js
> +            Mandatory fields are labeled with <span className="star">*</span>
Good practice is to store text that is visible to user in some constants. That way you can reuse it and easier add multilanguage functionality later

2021-07-21 12:17 UTC, Momir-Radovanovic-EY commented on src/containers/AppWizzardForm/ThirdWizardStep/ThirdWizardStep.js
> +              id={index}
I didn't find a better way to solve this. Index that I'm passing, I'm using it later to iterate through the array of convictions.

2021-07-23 07:39 UTC, mrdjan-stajic-ey requested changes
Great work so far the app works, but I noticed something, on the first step you can enter any number on the year, try it, i think validation should be aligned with that, on the second step i can enter the negative value on the How many years have you lived here, and that breaks the app after application. Also I the City/Town dropdown makes my Chrome freezes for a some time, there is some issue about that, please confirm if that is happening on your machine, or there is something wrong with my setup. About other comments, please apply the fixes on every occurrence of the similar/same problem

2021-07-23 07:39 UTC, mrdjan-stajic-ey commented on src/components/Carousel/Carousel.js
> +  if (windowDimensions < responsiveCarouselSettings["sm"]) {
Hey, this logic about responsiveness of the carousel should be moved to some function that is just invoked here since it should return the showNumberOfSlieds and all the data (window size, and responsive settings) are accessible from everywhere it would be easy to move it to some function for utils

2021-07-23 07:39 UTC, mrdjan-stajic-ey commented on src/components/Button/Button.js
> +Button.propTypes = {
Nice work for using prop types :)

2021-07-23 07:39 UTC, mrdjan-stajic-ey commented on src/components/Carousel/Carousel.js
> +  const numOfSliderPages = useMemo(() => {
Mini optimization, I like it, this is not bad, but the fact that you should have in mind that usage of useMemo will consume some resources from the app, so there is no need for this kind of optimization, but for learning purposes this is fine

2021-07-23 07:39 UTC, mrdjan-stajic-ey commented on src/components/Carousel/Carousel.js
> +        style={
Hey, inline styles should be avoided, you can add/remove a class based on the property.

2021-07-23 07:39 UTC, mrdjan-stajic-ey commented on src/components/Carousel/Carousel.js
> +              onClick={(e) => setNavigationBullet(e)}
Anonymous function can be avoided here since, div on click is sending the event data by default to the handler function so no need for passing the e to the handler in a anonymous function .

2021-07-23 07:39 UTC, mrdjan-stajic-ey commented on src/components/WizardLayout/WizardLayout.js
> +              dispatchingStepTrackerDecrement();
Also this, since userData is stored in some store, and the handler function can be extracted from the render function, and just call it from there.

2021-07-23 07:39 UTC, mrdjan-stajic-ey commented on src/components/WizardLayout/WizardLayout.js
> +              if (stepLvl === 0) {
Same applies here, step lvl is visible outside of render function, and can be extracted from the render function, all the data is visible as far as i can see

2021-07-23 07:39 UTC, mrdjan-stajic-ey commented on src/containers/AppWizzardForm/FirstWizardStep/FirstWizardStep.js
> +    let validatedSurname = validation(
All the validations should be also stored in some utils file and to receive all data needed for the validation

2021-07-23 14:41 UTC, Momir-Radovanovic-EY commented on src/components/Carousel/Carousel.js
> +              onClick={(e) => setNavigationBullet(e)}
Event data is default? I didn't know that :-O

2021-07-27 07:54 UTC, mrdjan-stajic-ey approved these changes
Nice job :) the app works great, it looks great also! Everything we talked about previously was addressed, again great job! 🥇

2021-07-27 07:54 UTC, merged